[tool.poetry]
name = "simdynamics"
version = "0.1.0"
description = ""
authors = ["David Browne <davidbrowne@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jax = "*"
jaxlib = "*"
scipy = "*"

[tool.poetry.dev-dependencies]
genty = "*"
